package it.thefedex87.bletest.utils

const val TAG: String = "ANDROID_BLE_TEST_DEBUG"

const val REQUEST_ENABLE_BT: Int = 1001
const val REQUEST_FINE_LOCATION_PERM: Int = 2001

const val INTENT_EXTRA_DEVICE_ID = "INTENT_EXTRA_DEVICE_ID"
const val INTENT_EXTRA_CHARACTERISTIC_UUID = "INTENT_EXTRA_CHARACTERISTIC_UUID"
const val INTENT_EXTRA_SERVICE_UUID = "INTENT_EXTRA_SERVICE_UUID"

const val ACTION_GATT_CONNECTED = "ACTION_GATT_CONNECTED"
const val ACTION_GATT_DISCONNECTED = "ACTION_GATT_DISCONNECTED"